### ISSUE TITLE
Please add a proper licence file

### ISSUE THREAD

**Issue by nandgator** [elvistony/btech-seminar-template#1]
As mentioned in this [Quora post](https://www.quora.com/What-if-I-dont-include-a-license-in-my-public-GitHub-project-Can-people-do-anything-with-my-code):

> According to Brian Doll, GitHub's VP of Marketing
> > Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.

Regards
Joe

**Comment by elvistony** [comment]
I'm not sure which license is involved (or even if there is a license). 
Could I instead Leave a link to his blog. I did modify the code a little to make it a bit more user friendly

Should I add "All Rights Reserved to Arun Xavier"
Blog:
https://arunxeee.blogspot.com/2015/03/btech-seminar-report.html 

P.S. I'm kinda new to github the licensing concept, please share your workaround this problem.

**Comment by nandgator** [comment]
This website gives a clear idea on [choosing a licence](https://choosealicense.com/). Once you have chosen a suitable licence, you'll find how to add one to an existing repository, [here](https://stackoverflow.com/a/52466628/).

In case you find any difficulty in adding a licence - just mention about the chosen licence and I'll open a PR accordingly.

**Comment by elvistony** [comment]
I'm assuming the Project works with the MIT License, since the source code and the files are free to use.
Anyways, I'll be contacting him soon to know more, till then. MIT should suffice i think.
Please make a PR if you can.
